/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { forwardRef } from "react";

type GLTFResult = GLTF & {
  nodes: {
    shirt_retopo_UVs_subDiv_seams_Default: THREE.Mesh;
  };
  materials: {
    F: THREE.MeshStandardMaterial;
  };
};

const filePath = "/assets/gltf/Mbtr_Shirt_v2-transformed.glb";

const Model = forwardRef<THREE.Group>((props, ref) => {
  const { nodes, materials } = useGLTF(filePath) as GLTFResult;

  return (
    <group {...props} dispose={null} rotation={[Math.PI / 2, 0, 0]} ref={ref}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shirt_retopo_UVs_subDiv_seams_Default.geometry}
        material={materials.F}
      />
    </group>
  );
});

useGLTF.preload(filePath);

export { Model };
